apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutationwebhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutationwebhook
  template:
    metadata:
      labels:
        app: mutationwebhook
    spec:
      volumes:
        - name: certs
          secret:
            secretName: tls
      containers:
        - name: mutationwebhook
          image: apeddauacr.azurecr.io/mutationwebhook:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: certs
            mountPath: /etc/certs
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mutationwebhook
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mutationwebhook
  type: ClusterIP
