apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webhook-minio-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ensure this matches PV size
  storageClassName: local-storage  # Must match PV
  volumeName: webhook-minio-pv-node0  # Explicitly bind to the existing PV

