apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutationwebhook
webhooks:
  - name: mutationwebhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1"
    sideEffects: "None"
    timeoutSeconds: 30
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        resource-webhook-enabled: "true"
    clientConfig:
      service:  
        namespace: default
        name: mutationwebhook
        path: "/mutate"
        port: 8080
      caBundle: "CA-CERT"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]