apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    app: test
spec:
  containers:
  - name: python-container
    image: python:3.9
    command: ["/bin/sh", "-c"]
    args:
      - "python3 /app/script.py"
    volumeMounts:
    - name: script-volume
      mountPath: /app
    - name: local-storage-volume
      mountPath: /mnt/disk1/data
  volumes:
  - name: script-volume
    configMap:
      name: test-script
  - name: local-storage-volume
    persistentVolumeClaim:
      claimName: webhook-minio-pvc