apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutationwebhook
webhooks:
  - name: mutationwebhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1"
    sideEffects: "None"
    timeoutSeconds: 30
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        resource-webhook-enabled: "true"
    clientConfig:
      service:  
        namespace: default
        name: mutationwebhook
        path: "/mutate"
        port: 8080
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVXVENDQTBHZ0F3SUJBZ0lVREU3K0JZQVVWdkdZb2w3ZUg5eE1xK2RXMEdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1V6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVUTUJFRwpBMVVFQ2d3S1FXTnRaU3dnU1c1akxqRVZNQk1HQTFVRUF3d01RV050WlNCU2IyOTBJRU5CTUI0WERUSTFNRFF3Ck16RXpNRFkwTjFvWERUSTJNRFF3TXpFek1EWTBOMW93Y0RFTE1Ba0dBMVVFQmhNQ1EwNHhDekFKQmdOVkJBZ00KQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVUTUJFR0ExVUVDZ3dLUVdOdFpTd2dTVzVqTGpFeU1EQUdBMVVFQXd3cApiWFYwWVhScGIyNTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdzBhdzhjaDBweGlHVWlXTTN0alhhS09rOXI2b2sKMWttV0RlV1VYOUFINVNZSW1jWVZVVEovdE94dnh3cXgxV1orcC9qVks2NmRVcmx0akFPRmZwdGJhc2x5U0JxWgpuYnJ0Y0grUW05Q202ZU9qVlMrMG1MbWdHbUp0NkJTekRPNmNQbmFna09hOGFmSjYrcFVyNkdYRnA1VVNEZENYCkFWeHpHOUdlWkxlNWZKTm1vL294ZTNuVUZpTFlMWFFCUEtkK1ZGYy8zUjA0eGtjMW00alpJTmM5WDUrTURjVW8KQ3I2M28yMzFzY0tXeXRidmhsRm8xVXpFZ0c3SGhRempQMDBsZmdCVTMrS2JwbU00T2hIek5DaXJIV1N1QnNLbQpHNS96akJEcmZZNzQ4VVByUHRqNGhBZEFiam5TZHByZm44MFhlc1lMMkZiZExZSTJiL2c1ZjVYN0FnTUJBQUdqCmdnRUdNSUlCQWpDQnZ3WURWUjBSQklHM01JRzBnaWx0ZFhSaGRHbHZibmRsWW1odmIyc3VaR1ZtWVhWc2RDNXoKZG1NdVkyeDFjM1JsY2k1c2IyTmhiSUlqYlhWMFlYUnBiMjUzWldKb2IyOXJMbVJsWm1GMWJIUXVjM1pqTG1OcwpkWE4wWlhLQ0cyMTFkR0YwYVc5dWQyVmlhRzl2YXk1a1pXWmhkV3gwTG5OMlk0SWJiWFYwWVhScGIyNTNaV0pvCmIyOXJMbVJsWm1GMWJIUXVjM1pqZ2hkdGRYUmhkR2x2Ym5kbFltaHZiMnN1WkdWbVlYVnNkSUlQYlhWMFlYUnAKYjI1M1pXSm9iMjlyTUIwR0ExVWREZ1FXQkJRVWE1NzZrakVwMkdSZXYzMDVKSjlMNEQ4NzVEQWZCZ05WSFNNRQpHREFXZ0JSa2J3KzExcElkejE4ZXJjcjhSRzM3R25od3pUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmNVZqCm8zekliWEQxdVFsekNmUmVQSmJyMmc3VnZXVU5BdjRYU0xQaW0xbXpaaFNqODV4NU5uZWd4TzNjRHMvcnpkL0UKWjBkWjgvaFZtWmZGOFducXRlanhoRm1Ea3ZKWHJWcW9zNGpyQ0lvUWROcVJSNzMxWG9BSTJjS2w1T2g0YmFGUgo4ME5ESjZxSUczL3Y1ZVdWbW0rcEtzcjdtMnE1VlJXakVYWmt5S1dEQWZ3Uk1GbHlaTFFQcndFK1hjTXhFcTNBCmlOK2U5STNDdVp5L1RuYzE4WkhyQjFKUkREd2FadFRXM3BRTFB4NVVCM2RWWm9QRjlMRW5CT1ZYRWJkL3Z4MDIKbnpSZzBLMkQ5VkMra1JhbVIxQnNQbytrMDVETVYzY2lxN3plaFViYzRaWURkbW9lWVZTek00RjRqcHAwdzhMNwo4eFVRWnRzNFhPd0hpeTQzcmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]